<link href="<?php printf("%s/css/jquery.fancybox-1.3.4.css", $this->baseUrl()); ?>" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php printf("%s/js/jquery.fancybox-1.3.4.js", $this->baseUrl()); ?>"></script>
<div id="inspiration-mainwrapper">
    <?php
    foreach ($this->inspirationList as $key => $value) {
        $image_path = $value->file_path . "images/" . $value->file_name;
        $info = pathinfo($value->file_name);
        $cssName = basename($value->file_name, '.' . $info['extension']);
        // $cssName = strstr($value->file_name, '.', true);
        if (is_file($this->basePath() . $this->theme('themes/default/css/' . $cssName . '.css'))) {
            ?>            
            <link href="<?php echo $this->theme('themes/default/css/' . $cssName . '.css') ?>" rel="stylesheet" type="text/css" />
        <?Php } ?>
    <!-- <link href="<?php echo $this->theme('themes/default/css/inspiration-elephant-bath.css') ?>" rel="stylesheet" type="text/css" />-->

        <div class="inspiration" style="background:url('<?php echo $this->baseUrl() . $image_path ?>')">

            <div id="inspiration-content-wrapper">
                <div id="inspiration-left-wrapper">
                    <div id="inspiration-left-inner-wrapper">
                        <div class="inspiration-text-blocks-wrapper">     
                            <div class="inspiration-text-block1">

                                <?php echo $value->description ?> 

                            </div>
                            <div class="inspiration-text-block1-content"> 
                            <?php } ?></div>

                        <?php
                        $params = sprintf("inspire_id=%s&rand=%s", $value->inspire_id, rand());
                        $cipherQuery = $this->rijndael->encrypt($params);
                        ?>
                        <div class="inspirations-comments">
                            <div class="inspiration-share-elephant-bath">
                                <a id="add-comment-to-inspire" href="<?php echo $_SERVER['REQUEST_URI']; ?>">Add Your Comment</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a class ="story" href="/inspiration/story">Post Your Story</a>
                                <div class="inspiration-sharebuttons">
                                    <a href="http://www.facebook.com/share.php? u=<?php echo $this->siteUrl() . $this->url; ?>" onclick="return fbs_click()" target="_blank" title="Face Book">
                                        <img src="<?php echo $this->theme('images/oval-fb-icon.png') ?>" alt="FaceBook" width="16" height="16" /> 
                                    </a>
                                    <a href="http://twitter.com/share?text=nepaladvisor&url=<?php echo $this->siteUrl() . $this->url; ?>" target="_blank" title="Twitter">

                                        <img src="<?php echo $this->theme('images/oval-twitter-icon.png') ?>" alt="Twitter" /> 
                                    </a>
                                    <a title="Digg" href="http://digg.com/submit?&jump=close&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'diggs','toolbar=no,width=1020,height=600'); return false;" onclick="window.open('http://digg.com/submit?&jump=close&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'digg','toolbar=no,width=1020,height=600'); return false;">
                                        <img src="<?php echo $this->theme('images/oval-digg-icon.png') ?>" alt="Digg" /> 
                                    </a>
                                    <a id="plusone-icon" class="pngfix" title="Google +" href="https://plusone.google.com/_/+1/confirm?hl=en&url=<?php echo $this->siteUrl() . $this->url; ?>&title=Nepal Advisor" target="_blank">
                                        <img src="<?php echo $this->theme('images/oval-gplus-icon.png') ?>" alt="Google+" />
                                    </a>
                                </div>
                                <div id="comment-wrapper" style="display:none;">
                                    <form action="<?php echo $this->siteUrl() . '/inspiration/comment/q/' . $cipherQuery; ?>" method="post">
                                        Title<br /><input name="title" id="comment-title" size="36"><br />
                                        Comment<br /><textarea id="comment-description" rows="6" cols="40"name="title" ></textarea><br />
                                        <input class="submit-comment-inspire" type="submit" name="submit" value="submit" id="signin_submit"/>
                                    </form>
                                </div>
                            </div>
                            <div class="inspirations-comments-elephant-bath-content">
                                <?php
                                if ($this->comments) {
                                    foreach ($this->comments as $comment):
                                        ?>
                                        <div class="inspirations-comments-elephant-bath-wrapper">
                                            <h2><?php echo $comment->title; ?> </h2>
                                            <?php echo $comment->description; ?>
                                            <?php echo htmlentities($comment->description, ENT_QUOTES, "UTF-8"); ?>
                                            <div class="commentor">
                                                <img src="<?php echo $this->theme('images/commentor-image.jpg') ?>" align="left" />
                                                <?php echo ($comment->full_name) ? $comment->full_name : $comment->email; ?>  <br />
                                                <?php echo $comment->date; ?>
                                                <div class="spam-flag">
                                                    <a class="report-spam" id="spam-<?php echO $comment->review_id; ?>" href="javascript:void(0);">Report a spam? </a>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                        <?php
                                    endforeach;
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="inspiration-right-wrapper">
                <?php
                echo $this->partial("blockListing/packageList.phtml", array('relatedPackage' => $this->relatedPackage, 'thumbPath' => $this->thumbPath, 'UploadDir' => $this->UploadDir, 'rijndael' => $this->rijndael));
                echo $this->partial('blockListing/inspirationList.phtml', array('relatedInspiration' => $this->relatedInspiration, 'rijndael' => $this->rijndael));
                ?>
            </div>

            <div class="clear"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        var customizeElement = {};
        $('.story').fancybox();
        $("#add-comment-to-inspire").click(function(e){
            e.preventDefault();
            $("#comment-wrapper").toggle();
        });
        $(".submit-comment-inspire").click(function(e){
            e.preventDefault();
            var title = $("#comment-title").val();
            var description = $("#comment-description").val();
            var commentUrl = $(this).parent().attr("action")
            if(user.hasIdentity){
                if(''==title){
                    alert("Please write title of review");
                    return false;
                }
                if(''==description){
                    alert("Please write description of review")
                    return false;
                }
            }else{
                alert("You need to log in to comment on this page");
                return false;
            }
            var data = {
                'title': title ,  
                'description': description 
            }
            $.ajax({               
                type:'POST',
                data: data,
                dataType:'json',
                url:commentUrl+'/format/json/',
                success:function(res){
                    if(res.isSubmited){
                        alert("Thanks for giving your review");
                        $("#comment-wrapper").hide();
                    }
                }
            });
        });
        $(".report-spam").click(function(){
            var spam = $(this).attr("id").split("-");
            var reviewId = spam[1];
            $.ajax({
                dataType:'json',
                url:site.baseUrl+'/inspiration/spam-report/q/'+reviewId+'/format/json/',
                success:function(res){
                    if(res.isSubmited){
                        alert("Thanks for submitting your report");
                    }
                }
            });
        });
    });
    
</script>