<?php //echo $this->form;?>
<div id="post-your-story-wrapper">
	<div id="post-your-story">
    	<div class="frm-post-story-label">Package Name:</div>
        <div class="frm-input-post-story"><input type="text" name ="title"/></div>
    	<div class="frm-post-story-label">Description:</div>
        <div class="frm-input-post-story"><textarea name ="description"></textarea></div>
       	<div class="frm-post-story-label">Image:</div>
        <div class="frm-input-post-story"><input type="file" name ="title"/><img src="images/activities-no-image-120.jpg"/></div>
        <div class="form-item"><input type="submit" class="form-submit" value="Save" id="submit" name="submit"></div>
    </div>
</div>