
<h1>FAQs</h1>
<div class="leftmaincol-content">
    <h3>1. What is NepalAdvisor?<br/></h3>
    NepalAdvisor is a comprehensive travel site offering a complete guide for your holiday in Nepal. The site is easily navigable and provides reliable information. This site seeks to present you with a customized holiday with a range of activities, based on your likes and preferences. 
    <br/><br/>
    <h3> 2. How to find holidays?<br/></h3>
    Choose from our default list of popular holidays by clicking on “Holiday Tab”. If you would like to have holidays customized to your preference, click on Places / activities in the top bar, select your place/activity of interest, followed by clicking on “Holidays” tab to find relevant holidays. Once you have found holiday of your choice, click on “book” and follow the instructions.
    <br/><br/>
    <h3>3. What is the meaning of “Likes”?<br/></h3>
    The website gives you an option to select and like places and activities of interest, based on which shall the website should relevant holidays. You can have multiple selections of places / activities.
    <br/><br/>
    <h3>4. Where can I select my places/activities of interest?<br/></h3>
    Hit on “Places” or “activities” to find a menu of touristic attractions in Nepal. You can do multiple selections of all that interests you and hence find relevant holidays.
    <br/><br/>
    <h3> 5. How can I know more about a particular place / activity?<br/></h3>
    To find more information on a particular place / activity, hover over the boxes / tiles and click on more.
    <br/><br/>
    <h3> 6. Can I purchase packages online?<br/></h3>
    Yes, through PayPal.<br/>
</div>