<div id="leftmaincol">
    <h1>Nepal Information</h1>
    <div class="leftmaincol-content">
    NepalAdvisor is a comprehensive travel site offering complete guide for your holiday in Nepal. We have tried to make it in a user-friendly and reliable manner, whereby you can choose the places and activities that interest you and we will recommended holidays.<br /><br /> 

    NepalAdvisor is a comprehensive travel site offering complete guide for your holiday in Nepal. We have tried to make it in a user-friendly and reliable manner, whereby you can choose the places and activities that interest you and we will recommended holidays.<br /><br /> 

    NepalAdvisor is a comprehensive travel site offering complete guide for your holiday in Nepal. We have tried to make it in a user-friendly and reliable manner, whereby you can choose the places and activities that interest you and we will recommended holidays. <br /><br />

    NepalAdvisor is a comprehensive travel site offering complete guide for your holiday in Nepal. We have tried to make it in a user-friendly and reliable manner, whereby you can choose the places and activities that interest you and we will recommended holidays. <br /><br />

    NepalAdvisor is a comprehensive travel site offering complete guide for your holiday in Nepal. We have tried to make it in a user-friendly and reliable manner, whereby you can choose the places and activities that interest you and we will recommended holidays. 				<br /><br />
</div>
</div>




