<?php
echo $this->grid;
?>
<script type="text/javascript">
$(function(){
    $('select').addClass('form-select');
    $('input[type="text"]').addClass('form-text').css('height','15px').css('width','100px');
    $('input[type="text"]#filter_date_from').addClass('form-text').css('height','15px').css('width','50px');
    $('input[type="text"]#filter_date_to').addClass('form-text').css('height','15px').css('width','50px');
});
</script>