<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/custompackage.css'); ?>
<link href="<?php printf("%s/css/jquery.fancybox-1.3.4.css", $this->baseUrl()); ?>" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="<?php printf("%s/js/jquery.validate.min.js", $this->baseUrl()); ?>"></script>
<script type="text/javascript" src="<?php printf("%s/js/jquery.fancybox-1.3.4.js", $this->baseUrl()); ?>"></script>
<script type="text/javascript">
    function number_format(number,decimals,dec_point,thousands_sep){var n=!isFinite(+number)?0:+number,prec=!isFinite(+decimals)?0:Math.abs(decimals),sep=(typeof thousands_sep==='undefined')?',':thousands_sep,dec=(typeof dec_point==='undefined')?'.':dec_point,s='',toFixedFix=function(n,prec){var k=Math.pow(10,prec);return''+Math.round(n*k)/k;};s=(prec?toFixedFix(n,prec):''+Math.round(n)).split('.');if(s[0].length>3){s[0]=s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,sep);}
    if((s[1]||'').length<prec){s[1]=s[1]||'';s[1]+=new Array(prec-s[1].length+1).join('0');}
    return s.join(dec);}

    $(function() {
        var customizeElement = {};
        $('.customize-ln-hotel, .customize-ln-transport').fancybox({
            //$customize-itenary = $(this);
            showActivity: true,
            centerOnScroll: true,
            onComplete: function(element, index, fb) {
                customizeElement.link = $(element);
            },
            ajax: {}
        });
        
        $( "#fromdate" ).datepicker({
            dateFormat: 'd M, yy',
            changeYear: true,
            buttonImage: "images/calendar.gif",
            buttonImageOnly: false,
            hideIfNoPrevNext: true
        });
        
        $.validator.addMethod("greaterThan", 
        function(value, element, params) {
            if (!/Invalid|NaN/.test(new Date(value))) {
                return new Date(value) > new Date($(params).val());
            }
            
            return isNaN(value) && isNaN($(params).val()) 
                || (Number(value) > Number($(params).val())); 
        },'Must be greater than {0}.');
        
        $('.customize-itenary-link-change').click(function() {
            $(this).parents('.customize-itenary-inner').find('.customize-itenary-link-dtl').toggle();
        });
        $('.choose-itenary').live("click",function(){
            var customizeParent = customizeElement.link.parents('.customize-itenary-inner');
            var myparent = $(this).parents('tr:first');
            
            //to replace current row of itenary
            var element_dtl_id = myparent.find('.element-detail-id').val();
            var name = myparent.find('td:first').text(); 
            var hotel = myparent.find('td:eq(1)').text() ;
            var service = myparent.find('td:eq(2)').text();
            var serviceType = myparent.find('td:eq(3)').text(); 
            customizeParent.find('.customize-itenary-title').text(name + ' ' + hotel);
            customizeParent.find('.customize-itenary-service').text(service + ' ' + serviceType);
            customizeParent.find('.hidden-element-id').val(element_dtl_id);
            
            // to replace total price with new price total
            var newPrice = Number($.trim(myparent.find('.price-per-element').text()));
            var oldPrice = Number($.trim(customizeParent.find('.customize-itenary-price').text()));
            
            var oldTotalPrice = Number($.trim($('#grand-total-cost').text()));
            var newTotalPrice = oldTotalPrice-oldPrice+newPrice;
            
            customizeParent.find('.customize-itenary-price').html(newPrice);
            $('.total-cost-itenary-hidden').val(newTotalPrice);
            $('#customize-cost-value').html('$'+number_format(newTotalPrice, 2));
            $('#grand-total-cost').html(newTotalPrice);
            $('a#fancybox-close').trigger('click');
            return false;
        });
        $('.choose-transport').live("click",function(){
            var customizeParent = customizeElement.link.parents('.customize-itenary-inner');
            var myparent = $(this).parents('tr:first');
            var element_dtl_id = myparent.find('.element-detail-id').val();
            var title = myparent.find("td:first").text();
            var service = myparent.find('td:eq(1)').text();
            var serviceType = myparent.find('td:eq(2)').text();
            customizeParent.find(".customize-itenary-title").text(title);
            customizeParent.find('.customize-itenary-service').text(service + ' ' + serviceType);
            customizeParent.find('.hidden-element-id').val(element_dtl_id);
           
            // to replace total price with new price total
            var newPrice = Number($.trim(myparent.find('.price-per-element').text()));
            var oldPrice = Number($.trim(customizeParent.find('.customize-itenary-price').text()));
            var oldTotalPrice = Number($.trim($('#grand-total-cost').text()));
            var newTotalPrice = oldTotalPrice-oldPrice+newPrice;
            customizeParent.find('.customize-itenary-price').html(newPrice);
            $('.total-cost-itenary-hidden').val(newTotalPrice);
            $('#customize-cost-value').html('$'+number_format(newTotalPrice, 2));
            $('#grand-total-cost').html(newTotalPrice);
            $('a#fancybox-close').trigger('click');
            return false;
        });
        
    });
</script>
<div id="customize-package">
    <?php if ($this->package) { ?>
        <form id="test" method="post" action="/default/package/update">
            <div id="package-configuration-wrapper">
                <div id="package-configuration-leftpanel">
                    <input type="hidden" name="event_id" value="<?php echo $this->package->event_id; ?>" />
                    <h2>Your Selected Trip</h2>
                    <div><h3><?php echo $this->package->title; ?></h3>
                        <?php
                        if ($this->package->file_name) {
                            $filename = $this->package->file_name;
                            $thumbpath = 'package' . DS . 'thumbnails' . DS . '120x120' . DS . 'images' . DS . $filename; 
                            if (is_file($this->basePath() . DS . $thumbpath)) {
                                printf("<div class='img-thumbnail'><img src='%s/package/thumbnails/120x120/images/%s' /></div>", $this->baseUrl(), rawurlencode($filename));
                            }
                        }
                        ?>
                        <div class="desc word-limiter-text-trimmed">
                            <?php
                            $outputText = $this->wordLimiter(strip_tags($this->package->description), 450);
                            print $outputText['text'];
                            ?><br />
                            <?php if ($outputText['isTrimmed']) : ?>
                                <a class="read-more" href="<?php echo $_SERVER['REQUEST_URI']; ?>">more...</a>                        
                            <?php endif; ?>
                        </div>
                        <div class="desc word-limiter-text-all" style="display:none;">
                            <?php print $this->package->description; ?><br />
                            <a class="read-less" href="javascript:void(0);">...less</a>
                        </div>
                        <div class="clear"></div>

                    </div>
                    <div class="eightpxseparator"></div>
                    <div class="configuration-packagefacts">
                        <div class="inforow"><strong>Duration:</strong>  
                            <?php echo $this->packageDetail[sizeof($this->packageDetail)-1]->day . " days"; ?>
                        </div>
                        <div class="inforow"><strong>Grade:</strong> Easy</div>
                        <div class="inforow"><strong>Price:</strong> 
                            <span id="customize-cost-value">$<?php echo number_format($this->package->total_price, 2); ?></span>
                            <span id="grand-total-cost" style="display:none;"><?php echo $this->package->total_price?></span>
                        </div>
                        <div id="total-cost-itenary-hidden">
                            <input class="total-cost-itenary-hidden"type="hidden" name="total_price" value="<?php echo $this->package->total_price; ?>" />
                        </div>

                        <div class="inforow"><span class="txtsmall">Including Taxes</span></div>
                    </div>
                    <div class="eightpxseparator"></div>
                </div>
                <div id="package-configuration-main">
                    <div><h1>Edit Your Trip</h1></div>
                    <span class="form-validation-errors">
                               <?php echo $this->partial("_flashMessages.phtml"); ?>
                    </span>
                    <fieldset><legend>Duration</legend>
                        <div class="eightpxseparator"></div>
                        <div class="fromdatepicker">
                            
                            <div class="fromdate">Date</div>
                            <div class="datepickertxtbx"><input type="text" readonly="readonly" id="fromdate" name="start_dt"placeholder="exact start date" value="<?php echo $this->package->start_dt; ?>"/></div>
                            
                        </div>
                        <!--<div class="todatepicker">
                            <div class="todate">To</div>
                            <div class="datepickertxtbx"><input type="text" id="todate" name="end_dt" disabled="disabled" placeholder="exact end date" /></div>
                        </div>-->
                    </fieldset>	


                    <div class="eightpxseparator clear"></div>
                    <div class="eightpxseparator"></div>
                    <fieldset><legend>Number of People</legend>
                        <div>
                            <select name="adult" class="cmbnumpeople">
                                <option value="">Adults</option>
                                <?php for ($i = 1; $i < 10; $i++) { ?>
                                    <?php $selected = ($this->package->adult == $i) ? 'selected' : ''; ?>
                                    <option <?php echo $selected; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                <?php } ?>
                            </select>&nbsp;&nbsp;

                            <select name="child" class="cmbnumpeople">
                                <option value="">Children</option>
                                <?php for ($i = 0; $i < 10; $i++) { ?>
                                    <?php $selected = ($this->package->child == $i) ? 'selected' : ''; ?>
                                    <option <?php echo $selected; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                <?php } ?>
                            </select>&nbsp;&nbsp;
                        </div>
                    </fieldset>
                    <div class="eightpxseparator"></div>
                    <div class="eightpxseparator"></div>
                    <div class="flightbook"><input type="checkbox"> Tick here if you need tickets to come to Nepal.</div>
                    <div class="clear"></div>

                    <div class="eightpxseparator"></div>

                    <hr />
                    <h2>Configure you itinerary</h2>
                    <div class="changes-instruction">
                        Below is your itinerary. You can make some changes by clicking on "change". For other changes you wish to make, please contact us online or by email and we will be glad to assist you with your changes.                      
                    </div>
                    <div class="eightpxseparator"></div>
                    <div class="eightpxseparator"></div>
                    <div id="top-utility-bar">
                        <div class="configuration-utility-wrapper">
                            <input class="button" type="submit" name="submit" value="Update" />
                            <!--<input class="button" type="submit" name="submit" value="proceed to checkout" disabled="disabled"/>-->
                        </div>
                        <div class="clear"></div>
                    </div>


                    <div id="customize-itenary">
                        <div id="customize-itenary-inner">
                            <?php $index = 0; ?>
                            <div id="customize-itenary-detail">
                                <div id="customize-itenary-detail-inner">
                                    <?php foreach ($this->packageDetail as $key => $detail) : ?>
                                        <?php $oe = ( ($key + 1) % 2 == 0 ? 'even' : 'odd'); ?>
                                        <div id="customize-itenary-<?php print $key + 1; ?>" class="customize-itenary <?php print $oe; ?>">
                                            <div class="customize-itenary-inner">
                                                <?php
                                                if ($key > 0) {
                                                    if ($this->packageDetail[$key - 1]->day == $this->packageDetail[$key]->day) {
                                                        $index++;
                                                    } else {
                                                        $index = 0;
                                                    }
                                                }
                                                ?>
                                                <input class="hidden-element-id" type="hidden" name="element_dtl_id[<?php echo $detail->event_dtl_id; ?>]" value="<?php echo $detail->element_dtl_id; ?>" />
                                                <div class="customize-itenary-price">
                                                    <?php printf("%d", $detail->price); ?>
                                                </div>
                                                <div class="customize-itenary-day float-left">
                                                    <?php printf("Day %d", $detail->day); ?>
                                                </div>


                                                <div class="customize-itenary-title float-left">
                                                    <?php print $detail->name . " - " . $detail->company_name; ?>
                                                </div>

                                                <div class="customize-itenary-service float-left">
                                                    <?php print $detail->service_class . " " . $detail->service_name; ?>
                                                </div>

                                                <div class="customize-itenary-link float-left">
                                                    <?php
                                                    $params = sprintf("element_dtl_id=%s&element_id=%s&location_id=%s&company_id=%s&service_name_id=%s&service_class_id=%s&to_location_id=%s", $detail->element_dtl_id, $detail->element_id, $detail->location_id, $detail->company_id, $detail->service_name_id, $detail->service_class_id, $detail->to_location_id);
                                                    $rijndael = new NepalAdvisor_Rijndael_Encrypt();
                                                    $cipherQuery = $rijndael->encrypt($params);
                                                    switch ($detail->element_id) {
                                                        case '2' :
                                                            printf("<a class=\"customize-ln-hotel\" href=\"%s/default/package/customize-hotel/format/html?q=%s\">Change</a>", $this->baseUrl(), $cipherQuery);
                                                            break;
                                                        case '6':
                                                        case '7':
                                                            printf("<a class=\"customize-ln-transport\" href=\"%s/default/package/customize-transport/format/html?q=%s\">Change</a>", $this->baseUrl(), $cipherQuery);
                                                            break;
                                                    }
                                                    ?>
                                                </div>
                                                <div class="clear"></div>

                                                <div class="customize-itenary-link-dtl hidden">

                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div id="custom-package-id">
                                <input type="hidden" name="package_id" value="<?php echo $this->package->package_id; ?>" />
                                <input type="hidden" name="no_of_days" value="<?php echo $detail->day; ?>" />
                            </div>
                        </div>
                    </div>
                    <div id="bottom-utility-bar">
                        <div class="configuration-utility-wrapper">
                            <input class="button" type="submit" name="submit" value="Update" />
                            <!--<input class="button" type="submit" name="submit" value="proceed to checkout" disabled="disabled"/>-->
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>

        </form>
        <?php
    } else {
        echo "<h3>You are not authorized to edit other's customized packages.</h3>";
    }
    $this->headScript()->appendFile('/js/utility.js');
    ?>
</div> 