
<!--******************************************* ACTIVITIES STARTS *******************************-->
<?php $session = Zend_Registry::get('defaultsession'); ?>
<?php
$data = array();
if (count($this->element) > 0) {
    foreach ($this->element as $res) {
        $data[$res['name']][$res['content_id']] = $res;
    }
    // var_dump($data);exit;
}
?>
<?php // id=#singlecolumn ?>
<div id="leftmaincol">
    <div id="activities">
        <?php
        if (count($data) > 0) {
            foreach ($data as $key1 => $item1) {
                ?>
                <h2><?php echo ucwords($key1); ?></h2>                      
                <div id="activities-scrollwrapper-<?php print strtolower($key1) ?>" class="activities-scrollwrapper"> 
                    <ul id="mycarousel-<?php print strtolower($key1) ?>" class="jcarousel-skin-tango jcarousel-activities">
                        <?php
                        foreach ($item1 as $key => $item) {
                            $selected = "";
                            $name = "Your Selected Likes";
                            $session->userlikecontent[$this->id] = is_array($session->userlikecontent[$this->id]) ? $session->userlikecontent[$this->id] : (array) $session->userlikecontent[$this->id];
                            if ($session->userlikecontent[$this->id] && $res['name'] != $name) {
                                if (array_key_exists($key, $session->userlikecontent[$this->id])) {
                                    $selected = "content-liked";
                                }
                            }
                            $thumb = 'uploads' . DS . 'thumbnails' . DS . '120x120' . DS . 'images' . DS . ($item['file_name']);
                            switch (trim($thumb)) {
                                case '':
                                case NULL:
                                case (!is_file($this->basePath() . DS . $thumb)) :
                                    $thumb = sprintf("%s/images/no-image/120x120.jpg", $this->baseUrl());
                                    break;
                                default:
                                    $thumb = $this->baseUrl() . '/uploads/thumbnails/120x120/images/' . rawurlencode($item['file_name']);
                            }
                            ?>

                            <li id="jcarousel-content-item-<?php print $key ?>" class="activities-item <?php echo $selected; ?> mrgn-bottom">
                                <div class="slide">
                                    <?php
                                    /**
                                     * append heading words with -
                                     */
                                    $headingParts = explode(' ', trim(strtolower($item['heading'])));
                                    $parts = array();
                                    // the looping is done to prevent multiple - to occur is more than one space
                                    // is in between two words
                                    foreach ($headingParts as $part) {
                                        if ($part) {
                                            $parts[] = $part;
                                        }
                                    }
                                    $title = implode('-', $parts);

                                    $id = $key;
                                    $catId = isset($item['element_category_id']) ? '-' . $item['element_category_id'] : '';
                                    $cipher = $this->rijndael->encrypt($id . $catId);
                                    $detailUrl = sprintf("%s/travel/%s/%s.html", $this->siteUrl(), $title, $cipher);
                                    $likeUrl = sprintf("%s/travel/%s/like/%s.html", $this->siteUrl(), $title, $cipher);
                                    $likeBtn = 'themes/default/themeimages/ic-like.png';
                                    $likeAltText = 'Like';
                                    $likeClass = 'ln-like';
                                    $likeImageClass = 'ln-img-like';
                                    if ($res['name'] == $name || $session->userlikecontent[$this->id]) {
                                        if ($res['name'] == $name || array_key_exists($key, $session->userlikecontent[$this->id])) {
                                            $likeUrl = sprintf("%s/travel/%s/removelike/%s.html", $this->siteUrl(), $title, $cipher);
                                            $likeClass = 'ln-unlike';
                                            $likeBtn = 'themes/default/themeimages/ic-unlike.png';
                                            $likeAltText = 'Unlike';
                                            $likeImageClass = 'ln-img-unlike';
                                        }
                                    }
                                    ?>
                                    <a class="img-ln <?php echo $likeClass; ?>" href="<?php print $likeUrl; ?>">
                                        <img src="<?php echo $thumb; ?>" title="<?php echo $item['one_line_desc'] ?>" alt="<?php echo $item['heading'] ?>" width="120" height="120" />
                                    </a>
                                    <span class="snipit">
                                        <a href="javascript:void(0);" class="content-infopop hover-icon"><img src="<?php echo $this->theme('themes/default/themeimages/ic-info.png') ?>" alt="Info" border="0" /></a> 
                                        <a href="<?php print $detailUrl; ?>" class="hover-icon-more">more</a>
                                        <a href="<?php print $likeUrl; ?>" class="hover-icon <?php echo $likeClass . ' ' . $likeImageClass; ?>"><img src="<?php echo $this->theme($likeBtn) ?>" alt="<?php echo $likeAltText; ?>" border="0" /></a>
                                    </span>
                                </div>
                                <div class="slide-caption">
                                    <span class="holiday-caption-title"><a href="<?php print $detailUrl; ?>"><?php echo $item['heading'] ?></a></span> 
                                    <br /><span class="holiday-caption-desc"><?php echo $item['one_line_desc']; ?></span>
                                </div>                                            
                                <input type="hidden" class="content-info-id" value="<?php echo $key ?>"/>    
                                <div id="detail-view-<?php echo $key; ?>" style="display:none">
                                    <h2><?php echo $item['heading']; ?></h2>
                                    <?php echo '<p>' . $item['three_line_desc'] . '</p>'; ?>
                                    <a href="<?php print $detailUrl; ?>" class="link-button">Details</a>

                                </div>
                            </li>
                        <?php }
                        ?>
                    </ul>
                    <div class="clear"></div>
                </div>
                <?php
            }
        } else {
            echo "<div class='notification-large'>No Records Found</div>";
        }
        ?>

    </div>
</div>

<div id="rightpanel">
    <div class="rightcontentbox">
        <h2>Book</h2>
        <?php
        foreach ($this->elementDetail as $dtl) {
            $params = sprintf("company_id=%s&element_dtl_id=%s", $dtl->company_id, $dtl->element_dtl_id);
            $cipherQuery = $this->rijndael->encrypt($params);
            ?>
                                <!--<h3><a href="<?php echo $this->siteUrl() . "/default/serviceprovider/detail/?q=$cipherQuery"; ?>"><?php echo ucwords(trim($dtl->name)); ?></a></h3>-->
            <div class="otherhotelslistwrapper">
                <form action="<?php echo $this->siteUrl() . "/serviceprovider/book"; ?>" method="post" >
                    <div class="otherhotelsthumb">
                        <?php
                        $fn = '';
                        if ($dtl->image_url) {
                            $fn = end(explode('/', $dtl->image_url));
                        }

                        $thumbPath = 'uploads' .DS . 'element' . DS . 'thumbnails' . DS . '120x120' .DS . 'images' . DS . rawurlencode($fn);
                        $thumbUrl = sprintf("%s/images/no-image/70x70.jpg", $this->baseUrl());
                        if (is_file($this->basePath() . DS . $thumbPath)) {
                            $thumbUrl = sprintf("%s/uploads/element/thumbnails/120x120/images/%s", $this->baseUrl(), $fn);
                        }
                        
                        $dtlUrl = $this->siteUrl() . "/default/serviceprovider/detail/?q={$cipherQuery}";
                        $dtlUrl = sprintf("%s/serviceprovider/element-detail?q=%s", $this->siteUrl(), $cipherQuery); 
                        $dtlUrl = "javascript:void(0)";
                        ?>
                        <a href="<?php echo $dtlUrl; ?>"><img height="70" width="70" src="<?php echo $thumbUrl; ?>" alt ="no-img"/></a>
                    </div>
                    <div class="otherhotelsdesc">
                        <h3 class="right-title"><?php echo $dtl->description; ?></h3>
                        <span class="holiday-caption-desc">Transportation: <?php echo ucwords($dtl->company_name); ?></span><br />
                        <span class="holiday-caption-desc">Price: $<?php echo number_format($dtl->price, 2) ?></span><br />         
                    </div>
                    <div class="clear"></div>
                    <div class="list-duration">
                        <?php $cip = $this->rijndael->encrypt('element-' . $dtl->element_dtl_id); ?>
                        <a class="back-button" href="<?php echo $this->siteUrl() . '/serviceprovider/book/' . $cip . '.html'; ?>" >Book Now</a>
                        <!--<input type="hidden" name="element_dtl_id" value="<?php echo $dtl->element_dtl_id; ?>" />
                        <input type="hidden" name="request_uri" value="<?php echo $_SERVER['REQUEST_URI']; ?>" />
                        <input type="submit" name="book" id="signin_submit" value="Book Now" />-->
                    </div>
                </form>
            </div>
<?php } ?>  
    </div>
</div>
<div class="clear"></div>
<?php
//} 
?>
