<fieldset>
    <legend><h2>Your new password</h2></legend>
    <form method="post" action="<?php echo $this->siteUrl() . '/users/password-recovery/id/' . $this->id; ?>" >
        <div class="form-item">
            <div id="password-label">
                <label class="required" for="password">Enter new password</label>
            </div>
            <div class="Label">
                <input type="password" size="30" value="" id="res-password" name="password">
            </div>
        </div>
        <div class="form-item">
            <div id="password-conf-label">
                <label class="required" for="password-conf">Re-enter your password</label>
            </div>
            <div class="Label">
                <input type="password" size="30" value="" id="res-password-conf" name="password-conf">
                <input type="hidden" name="code" value="<?php echo $this->activationCode; ?>" />
            </div>
        </div>
        <div class="form-item">
            <div class="Label">
                <input type="submit" value="Reset Your Password" id="signin_submit" name="submit">
            </div>
        </div>
    </form>
</fieldset>
<script type="text/javascript">
    $(document).ready(function(){
        $("#res-password, #res-password-conf").live("blur",function(){
            var password = $("#res-password").val();
            var passwordConf = $("#res-password-conf").val();
            if(password!=passwordConf && password && passwordConf){
                $("#res-password").val("");
                $("#res-password-conf").val("");
                alert("Passwords doesn't match");
            }
        });
        
    });
</script>