<h1>What is NepalAdvisor?</h1>
<div class="leftmaincol-content" style="text-align:justify;">
    <img src="<?php echo $this->theme('images/img-about-us.jpg')?>" alt="About Us" style="width:100%;"/>
    <div style="margin-top: 7px;">
    NepalAdvisor is a comprehensive travel site offering a complete guide for your holiday in Nepal. 
    We have tried to make it in a user-friendly and reliable manner, whereby you can choose places and activities that interest you and we will recommend holidays accordingly
    Information is the key. With so much to do in Nepal, the process of exploring never really comes to an end. 
    Through NepalAdvisor, we present to you a highly comprehensive list of all touristic places and activities in Nepal, giving you the scope to explore and learn about the place. 
    Our website seeks to be a platform of easily available information, with an option of reading about and exploring the place or activity before hand, to assist you in the making the right holiday decisions for Nepal.
    With in-depth articles and created multimedia, you get to experience the place before hand that will enable you to make the right travel decisions, without getting carried away by false and deceiving information. 
    We value your money and would like you to spend it on the right vacation, one that’s meant just for you.
    Our website helps you avoid choosing a package without knowing what’s its really about and thereby preventing you from committing to an unsuitable deal. 
    The content of the website, in its different sections, host precise information about a range of activities and tourist spots. 
    Browsing through the site will help you find the right elements for your holiday.
    We are currently based in Nepal with a team of hard-working developers and writers to provide you with the best possible experience in navigating through the website and help you find the information at an absolute ease. 
    In case of any confusion or problem, we also offer the facility of conversing with our expert in Nepal, in addition to the information on the website.

    <h1>How the site works?</h1>
    The site can be fully customized to your needs and preferences. 
    It works on the simple concept “You select and we present”. 
    This is as easy and simple as ordering your preferred meal off a restaurant menu!
    By hitting on the “places” or “activities” tab in the top bar, you are presented with a menu of all touristic places and 
    activities in Nepal. Suppose you are in the activities page, and you hit on rafting and trekking box, the site understands 
    that you have “liked” them and therefore presents you with all holiday options that follow your preferences.
    When you like a particular place or an activity, you are simply letting the system know your personal preferences. 
    You can do multiple selections or “Likes”. 
    The system’s backhand is intelligent and provides you with the most relevant holidays, based on your “Likes”. 
    At any point of time, you are free to select or de-select your likes and see appropriate holidays. 
    Should you not select any option as your “likes”, the site will show you a default list of popular holidays. 
    The list of holidays can be viewed by hitting on the “Holidays” tab.
    </div>
    <h1>Pictorial Guide:</h1>
    <img src="<?php echo $this->theme('images/pictorialhelp.jpg') ?>"><br/><br/>
    Hitting on “Holidays” tab takes you to the list of holiday tours in Nepal
    To find all touristic places of attractions in Nepal, hit on “Places” tab.
    Once you are in there, you are presented with a highly comprehensive list of touristic places.
    To find all touristic activities of interest, hit on “Activities” tab.
    When you are either in the “Places” tab or “Activities” tab, clicking once on the tiles or boxes highlights it 
    indicating that you like it. You can do such multiple “Likes”.
    You also have an option to read about a particular place or activity and learn more about it.
    Clicking on “More” when you hover over the tile or the box takes you to the content page, 
    where you can all relevant information on that particular place or activity.
    As when you have finished selecting all your “Likes”, click on holidays and find relevant holiday 
    packages based on your likes and preferences.
</div>




