<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/booking.css');
$form = $this->form->getElements(); ?>
<script src="jquery-components/ui/jquery.ui.datepicker.js" class="jsbin"></script>  
<div id="customize-package">
    <form action="" method="post" >
        <div id="package-configuration-wrapper">
            <div id="package-configuration-leftpanel">
                <?php
                if (isset($this->elementDetail)) {
                    $dtl = $this->elementDetail;
                    $arr = explode("/", $dtl->image_url);
                    $imageName = $arr[sizeof($arr) - 1];                  
                    ?>
                    <div class="description-element-detail">
                        <h2><?php echo $dtl->name . " at " . ucwords($dtl->company); ?></h2>
                        
                        <?php if (is_file($this->basePath() . DS . 'uploads' . DS . 'images' . DS . 'Element' . DS . 'thumbnails' . DS . '120x120' . DS . 'images' . DS . $imageName)) : ?>
                        <div class="img-field">
                            <img src="<?php printf("%s/uploads/images/Element/thumbnails/120x120/images/%s", $this->baseUrl(), rawurlencode($imageName)); ?>" />
                        </div>
                        <?php endif; ?>
                        
                        <span class="holiday-caption-title"><?php echo ucwords($dtl->servicename); ?> : </span>
                        <span class="holiday-caption-desc"><?php echo ucwords($dtl->serviceclass); ?></span><br />
                        <span class="holiday-caption-title">Price : </span>
                        <span class="holiday-caption-desc">$<?php echo ucwords($dtl->price); ?></span><br />
                        <span class="holiday-caption-title">Location : </span>
                        <span class="holiday-caption-desc"> <?php echo ucwords($dtl->Location); ?></span><br />
                        <span class="holiday-caption-title">Detail : </span>
                        <span class="holiday-caption-desc"> <?php echo ucwords($dtl->description); ?></span><br />
                        <span class="book-element">
                            <input type="hidden" name="element_dtl_id" value="<?php echo $dtl->element_dtl_id; ?>" />
                        </span>

                    </div>
                    <div class="clear"></div>
                <?php } elseif ($this->package) { ?>
                    <?php if (isset($this->package->event_id)) { ?>
                        <input type="hidden" name="event_id" value="<?php echo $this->package->event_id; ?>" />
                    <?php } else { ?>
                        <input type="hidden" name="package_id" value="<?php echo $this->package->package_id; ?>" />
                    <?php } ?>
                    <h2>Your Selected Trip</h2>
                    <div><h3><?php echo $this->package->title; ?></h3>
                        <?php
                        if (isset($this->package->file_name)) {
                            $filename = $this->package->file_name;
                            $thumbpath = 'package' . DS . 'thumbnails' . DS . '120x120' . DS . 'images' . DS . $filename; 
                            if (is_file($this->basePath() . DS . $thumbpath)) {
                                printf("<div class='img-thumbnail'><img src='%s/package/thumbnails/120x120/images/%s' /></div>", $this->baseUrl(), rawurlencode($filename));
                            }
                        }
                        ?>
                        
                        <div class="desc word-limiter-text-trimmed" style="font-size:12px;">
                            <?php
                            $outputText = $this->wordLimiter(strip_tags($this->package->description), 450);
                            print $outputText['text'];
                            ?><br />
                            <?php if ($outputText['isTrimmed']) : ?>
                                <a class="read-more" href="<?php echo $_SERVER['REQUEST_URI']; ?>">more...</a>                        
                            <?php endif; ?>
                        </div>
                        <div class="desc word-limiter-text-all" style="display:none;">
                            <?php print $this->package->description; ?><br />
                            <a class="read-less" href="javascript:void(0);">...less</a>
                        </div>
                        <div class="clear"></div>

                    </div>
                    <div class="eightpxseparator"></div>
                    <div class="configuration-packagefacts">
                        <div class="inforow"><strong>Duration:</strong>  
                            <?php
                            if (isset($this->package->no_of_days)) {
                                print $this->package->no_of_days ." days";
                            } else {
                                echo (strtotime($this->package->end_dt) - strtotime($this->package->start_dt)) / (60 * 60 * 24) . " days";
                            }
                            ?>
                        </div>
                        <div class="inforow"><strong>Grade:</strong> Easy</div>
                        <div class="inforow"><strong>Price:</strong> 
                            <span id="customize-cost-value">
                                <?php
                                if (!isset($this->package->total_price)) {
                                    echo '$' . number_format($this->package->total_cost, 2);
                                } else {
                                    echo '$' . number_format($this->package->total_price, 2);
                                }
                                ?></span></div>
                        <div class="inforow"><span class="txtsmall">Including Taxes</span></div>
                    </div>
                    <div class="eightpxseparator"></div>
                <?php } ?>
            </div>
            <div id="package-configuration-main">
                 <img src="<?php echo $this->baseUrl().'/images/step1-active.gif'; ?>" />
                 <?php print $this->partial('_flashMessages.phtml'); ?>
                 <div class="note-wrapper">
                    <span class="note">
                        <span>Note : </span>
                    Your booking does not include any confirmation on your air connections to and from Nepal. If you, however, require us to make the international air connections for you, please contact our help desk through email or telephone.
                    </span>
                 </div>
                <fieldset>
                    <legend><div><h2>Book Your Trip</h2></div></legend>
                    <div class="fromdatepicker">
                            <input type="hidden" name="request_uri" value="<?php echo $_SERVER['REQUEST_URI']; ?>" />
                            <div class="fromdate">Date</div>
                            <div class="datepickertxtbx">
                                 <?php if($this->fixDates){ ?>
                                <select id="fromdate" name="booking_dt" type="select">
                                    <?php foreach($this->fixDates as $date){
                                        $displayDate = new DateTime($date->date);
                                        ?>
                                    <option value="<?php echo $date->date; ?>"><?php echo $displayDate->format("d M Y"); ?></option>
                                    <?php } ?>
                                </select>    
                                <?php }else{ 
                                 echo "<div class='booking-date-wrapper'>".$form["booking_dt"]."</div>"; 
                                    } ?>
                            </div>
                            
                        </div>
                    </fieldset>	
                    <div class="eightpxseparator clear"></div>
                    <div class="eightpxseparator"></div>
                   <fieldset><legend>Number of People</legend>
                        <div>
                            <div id="adult-wrapper">
                                <?php echo $form["no_of_adult"]; ?>
                            </div>
                            <div id="children-wrapper">
                                <?php echo $form["no_of_children"]; ?><br />
                                <small>(age less than 5 years)</small>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </fieldset>
                    <div class="eightpxseparator"></div>
                    <div class="eightpxseparator"></div>
                    <div class="clear"></div>
                    <div class="eightpxseparator"></div>
                    <?php  echo $form["submit"]; ?>
                    <div class="eightpxseparator"></div>
                </fieldset>
            </div>
        </div>
        <div class="clear"></div>
    </form>
    <input id="cur-dt" type="hidden" name="cur_dt" value="<?php print date('Y-m-d'); ?>" />
    <?php $this->headScript()->appendFile('/js/utility.js');
    ?>
</div>
<script type="text/javascript">
     $(document).ready(function() {
         $("#fromdate").datepicker({
            dateFormat: 'd M, yy'
        });
    });
</script>